server: 
  port: ${PORT:8888}

spring:
  application:
    name: csc-config-server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/igpicotto/service-common-config
              